### ISSUE TITLE
Installation on google colab

### ISSUE THREAD

**Issue by dara1400** [uncertainty-toolbox/uncertainty-toolbox#20]
Hello
 I have tried to install the package in google colab according to your instruction.
It dose not work.
would you help me?

Thanks for the great package

**Comment by YoungseogChung** [comment]
Can you specify the issue you are running into when installing on Google Colab?
I can install it and run it on Google Colab without any problems right now.

**Comment by dara1400** [comment]
I use a cell like this:

!git clone https://github.com/uncertainty-toolbox/uncertainty-toolbox.git
%cd /content/uncertainty-toolbox
!pip3 install -e

**Comment by YoungseogChung** [comment]
`pip install -e .`

You forgot the dot

**Comment by dara1400** [comment]
Thanks a lot
