### ISSUE TITLE
"layman" definition of interval score using width and coverage

### ISSUE THREAD

**Issue by sgbaird** [uncertainty-toolbox/uncertainty-toolbox#61]
I'm trying to figure out how to describe the math behind interval score in a simple way. Based on reading the paper and related literature, I get that it incorporates width and coverage. Is the idea that it penalizes the following two scenarios:
- wide intervals
- when many predictions fall outside of the intervals

In other words, the interval should be as narrow as possible while having the interval "cross the parity line" as frequently as possible, correct? How does this play out in the math?

**Comment by sgbaird** [comment]
I'm also interested in why there is the factor: `(2.0 / (1 - p))` in the coverage penalties.

**Comment by YoungseogChung** [comment]
Hi @sgbaird, apologies for the slow reply.

You are exactly correct about your intuition of the interval score. 
In fact, the first bullet point is a notion of "sharpness", and the second, a notion of "calibration". The interval score is one example of a *proper scoring rule*, which are generally known to target calibration and sharpness simultaneously [1]. 
So, just as you said, when evaluating prediction intervals, the interval score encourages intervals that are as sharp (i.e. narrow) as possible, while being calibrated (i.e. the interval contains the correct proportion of datapoints). 

Regarding your second comment, there are multiple ways to look at this.
The first is from [2]. In this paper, the check score (i.e. the pinball loss) in Equation (41) is derived from a general proper scoring rule for quantiles (Eq. 40), and it is further shown that a summation of Eq. (41) over multiple quantiles is also a proper scoring rule (Corollary 1., Eq. 42). The interval score is derived from Eq (42) by setting a pair of quantile levels, $\frac{\alpha}{2}$ and $1-\frac{\alpha}{2}$ (Eq. 43), and setting functions for $s(x)$ and $h(x)$ that result in a symmetric and intuitive form for the score. Note here that the desired coverage level of the interval is $1-\alpha$, and thus $\alpha$ proportion of the points is expected to fall *outside* the interval. 

The multiplicative factor $\frac{2}{\alpha}$ is also specifically the factor that recovers the true quantiles at the score’s optimum (refer to Appendix A.4 of [3]).

From an intuitive perspective, the factor, $\frac{2}{\alpha}$ decides the weight between the sharpness and calibration objectives. If you are constructing 99% prediction intervals (i.e. $\alpha = 0.01$), you would be tolerant towards wide intervals, but less so towards datapoints falling outside the interval, hence, $\frac{2}{\alpha}$ heavily weights the calibration objective. The opposite case holds when alpha is very high.

[1] [Probabilistic forecasts, calibration and sharpness (Gneiting et. al., 2007)](https://sites.stat.washington.edu/raftery/Research/PDF/Gneiting2007jrssb.pdf)
[2] [Strictly Proper Scoring Rules, Prediction, and Estimation (Gneiting et. al., 2007)](https://sites.stat.washington.edu/raftery/Research/PDF/Gneiting2007jasa.pdf)
[3] [Beyond Pinball Loss: Quantile Methods for Calibrated Uncertainty Quantification (Chung et. al., 2020)](https://arxiv.org/pdf/2011.09588.pdf)

**Comment by sgbaird** [comment]
Cc @smichtavy
