### ISSUE TITLE
Convert from symmetric confidence intervals to standard deviation

### ISSUE THREAD

**Issue by sgbaird** [uncertainty-toolbox/uncertainty-toolbox#64]
Incorporating some code into another repository, and wanted to check with some people with (very likely) a more thorough statistics background than myself.

Conversion from standard deviation to confidence intervals takes place in: https://github.com/uncertainty-toolbox/uncertainty-toolbox/blob/b2f342f6606d1d667bf9583919a663adf8643efe/uncertainty_toolbox/metrics_scoring_rule.py#L187

What is the inverse conversion from symmetric confidence intervals back to standard deviation? (e.g. using `scipy.stats.norm` but doesn't have to be)

**Comment by sgbaird** [comment]
https://handbook-5-1.cochrane.org/chapter_7/7_7_3_2_obtaining_standard_deviations_from_standard_errors_and.htm
> If the sample size is large (say bigger than 100 in each group), the 95% confidence interval is 3.92 standard errors wide (3.92 = 2 × 1.96).

So `ci_upper - ci_lower` gives us confidence interval width, and for 95% confidence interval, this is ~3.92 standard deviations, so `std = (ci_upper - ci_lower) / 3.92`  or more generally:

```python
std = (pred_u - pred_l) / (2 * stats.norm.ppf(low_p))
```

Can I get a sanity check on this? (note I'm assuming two-sided confidence intervals for this)

**Comment by IanChar** [comment]
Hi @sgbaird sorry for the late reply. I think that you are correct subject to the prediction interval being a centered prediction interval (and of course using normal distribution).
