### ISSUE TITLE
Quantile Regression

### ISSUE THREAD

**Issue by velezbeltran** [uncertainty-toolbox/uncertainty-toolbox#80]
Hello!

Thanks for this convenient tool! I was wondering how you best suggest using it for quantile regression. I see that a lot of functions take in a pred-mean and std. However, I thought it would also be nice if there were additional support for quantiles and not only std + mean support. Is there a way of hacking my way through what is now so that I could use the quantile intervals I get instead?

**Comment by IanChar** [comment]
Hi @velezbeltran. Thanks for your question. There is some additional support for quantile models in the "quantile_models" branch that was contributed (Issue #39 ). Right now I believe this only works with pytorch models, which is an issue. We are still trying to think about the most robust way to incorporate this functionality into the main package.

I am going to close this issue for now to consolidate.
